### PR TITLE
Add in last 4 methods from Valve wiki, also redo entire test suite in mocha

### PR DESCRIPTION
**Pull request by vincegogh**
Hello,

I added the last 4 methods from the valve wiki, completing #9. While doing these methods I also undertook a whole remake of the test suite mainly because I found it a little annoying, I think it's a major improvement over the old tests, but if you want I can remove it. 

The diff is quite large because I added 2 dev dependencies and 1 normal dependency but here are the important things to note:
- Last 4 methods added from valve wiki
- Deleted old tests, also renamed folder from tests to test (because mocha runs the 'test' folder by default)
- Added newtests.js which has all the new tests in mocha, you can run them using `npm install` to install the extra modules then `npm test` to run the script.
- I added one normal dependency, the `qs` library for string parsing. It has pretty much the same functionality as the other module, except it has support for parsing arrays with indices such as `array[0]=something&array[1]=something` which I needed for one of the methods I added.
- I also cleaned up some random non-functioning or just odd code that I found, mostly removing random brackets and solidifying the object validations for each method.

And I do apologise for not making the commits well structured, I was moving a little bit between computers so had to commit at odd times. 

That's about it; if this gets merged I will probably make a new PR in the following days with the remaining methods from the TF2 wiki.

- Vincent

EDIT: I just realised I need to update the docs, I'll do that ASAP (today or tomorrow)

### CODE REVIEW

**Comment by Tidwell** [comment]
This is awesome.  biggest thing i think is adding node_modules to the gitignore, that'll make the merge a lot easier - I'll take a look at merging it in asap :)

**Comment by vincegogh** [comment]
I added it to the gitignore, but the diff still shows all the old files. Should I make a separate PR so you can view the diff nicely?

**Comment by vincegogh** [comment]
Nevermind, I just had to remove the files from my local cache then push those changes. Diff looks fine now

**Comment by Tidwell** [comment]
Awesome, I'll merge this later today.  I'll make sure to remove your API key, but you will probably want to go invalidate that in steam since its leaked in this commit.

**Comment by vincegogh** [comment]
Oh haha, thanks for the heads up. I thought I added it to gitignore... weird. Anyway, thanks

**Pull request merged**
